"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import { Player } from "@remotion/player";
import { ConceptCardVideo } from "@/remotion/compositions/ConceptCardVideo";
import {
    Sparkles, Loader2, RefreshCcw, AlertTriangle,
    CheckCircle, BookOpen, Video, Play, Pause
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

interface ConceptVideoPlayerProps {
    courseId: string;
    topic: string;
    customStoryboardText?: string;
}

// ─── 3-Level Progressive Output Architecture ─────────────────────────────────
// Level 1 (instant): Storyboard cards + Remotion preview in-browser
// Level 2 (fast): AI-enriched content from /api/media/plan
// Level 3 (slow/async): MP4 from Blob URL via /api/media/render job
// ──────────────────────────────────────────────────────────────────────────────

type VideoState =
    | "level1_instant"      // Remotion renders locally
    | "level2_enriching"    // AI enriching content
    | "level2_ready"        // AI-enriched Remotion preview ready
    | "level3_queued"       // MP4 render job queued
    | "level3_rendering"    // MP4 rendering in progress
    | "level3_ready"        // MP4 available from Blob URL
    | "error";

function generateLocalVideoProps(topic: string) {
    return {
        title: topic || "Konsep Fisika",
        keyPoints: [
            `Memahami konsep dasar ${topic}`,
            `Menganalisis fenomena ${topic}`,
            `Penerapan dalam kehidupan nyata`,
            `Strategi penyelesaian soal`,
        ],
        formula: "",
        style: "dark_premium" as const,
    };
}

export default function ConceptVideoPlayer({ courseId, topic, customStoryboardText }: ConceptVideoPlayerProps) {
    const [state, setState] = useState<VideoState>("level1_instant");
    const [videoData, setVideoData] = useState<any>(null);
    const [blobUrl, setBlobUrl] = useState<string | null>(null);
    const [jobId, setJobId] = useState<string | null>(null);
    const [progress, setProgress] = useState(0);
    const [errorMsg, setErrorMsg] = useState("");
    const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);

    // ── Level 1: Instant local render ────────────────────────────────────────
    useEffect(() => {
        const localProps = generateLocalVideoProps(topic);
        setVideoData(localProps);
        setProgress(25);

        // ── Level 2: Background AI enrichment ────────────────────────────────
        const enrichTimer = setTimeout(() => {
            setState("level2_enriching");
            fetch("/api/media/plan", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    topic,
                    courseId,
                    questionText: customStoryboardText, // Force the AI to use the exact storyboard text generated by the Universal Tutor
                    pedagogicalNeed: "concept_visualization",
                    formulaDensity: customStoryboardText ? 0.8 : 0.1, // If we have specific text, it's likely a math/physics problem
                    outputType: "video",
                }),
            })
                .then(res => res.ok ? res.json() : null)
                .then(data => {
                    if (!data) {
                        setState("level2_ready"); // Use local props, still fine
                        setProgress(50);
                        return;
                    }
                    const brief = data?.data || data;
                    const enrichedProps = {
                        title: brief?.title || localProps.title,
                        keyPoints: brief?.keyPoints || brief?.bulletPoints || localProps.keyPoints,
                        formula: brief?.formula || "",
                        style: "dark_premium" as const,
                    };
                    if (enrichedProps.title && enrichedProps.keyPoints?.length > 0) {
                        setVideoData(enrichedProps);
                    }
                    setState("level2_ready");
                    setProgress(50);
                })
                .catch(() => {
                    setState("level2_ready"); // Graceful fallback
                    setProgress(50);
                });
        }, 500); // Small delay so Level 1 shows first

        return () => {
            clearTimeout(enrichTimer);
            if (pollRef.current) clearInterval(pollRef.current);
        };
    }, [topic, courseId]);

    // ── Level 3: Poll job status (if job was created) ────────────────────────
    useEffect(() => {
        if (!jobId) return;

        pollRef.current = setInterval(async () => {
            try {
                const res = await fetch(`/api/jobs/${jobId}`);
                if (!res.ok) return;
                const job = await res.json();

                if (job.status === "completed" && job.outputUrl) {
                    setBlobUrl(job.outputUrl);
                    setState("level3_ready");
                    setProgress(100);
                    if (pollRef.current) clearInterval(pollRef.current);
                } else if (job.status === "failed") {
                    // Stay on Level 2 — Remotion preview still works
                    setState("level2_ready");
                    setProgress(50);
                    if (pollRef.current) clearInterval(pollRef.current);
                } else if (job.status === "running") {
                    setState("level3_rendering");
                    setProgress(75);
                }
            } catch {
                // Ignore poll errors
            }
        }, 8000); // Poll every 8 seconds

        return () => {
            if (pollRef.current) clearInterval(pollRef.current);
        };
    }, [jobId]);

    // ── Status label for current state ───────────────────────────────────────
    const statusLabel = {
        level1_instant: "Preview Instan",
        level2_enriching: "AI Memperkaya Konten...",
        level2_ready: "Preview AI",
        level3_queued: "Merender MP4...",
        level3_rendering: "Merender Video HD...",
        level3_ready: "Video HD Siap",
        error: "Error",
    }[state];

    const statusColor = {
        level1_instant: "text-blue-400",
        level2_enriching: "text-yellow-400",
        level2_ready: "text-green-400",
        level3_queued: "text-orange-400",
        level3_rendering: "text-orange-400",
        level3_ready: "text-emerald-400",
        error: "text-red-400",
    }[state];

    if (state === "error") {
        return (
            <div className="w-full aspect-video rounded-2xl overflow-hidden border border-red-500/20 bg-red-950/20 flex flex-col items-center justify-center gap-3">
                <AlertTriangle className="w-8 h-8 text-red-400" />
                <p className="text-red-300 text-sm">{errorMsg || "Gagal memuat video"}</p>
                <button
                    onClick={() => {
                        setState("level1_instant");
                        setVideoData(generateLocalVideoProps(topic));
                    }}
                    className="flex items-center gap-2 px-4 py-2 bg-red-500/20 hover:bg-red-500/30 text-red-300 rounded-lg text-xs transition-colors"
                >
                    <RefreshCcw className="w-3.5 h-3.5" /> Coba Lagi
                </button>
            </div>
        );
    }

    // Show Remotion player for Level 1 & 2, or HTML5 video for Level 3
    return (
        <div className="w-full relative rounded-2xl overflow-hidden border border-white/10 bg-black/40 shadow-2xl group">
            {/* Progress bar */}
            <div className="absolute top-0 left-0 right-0 h-1 bg-white/5 z-20">
                <motion.div
                    className="h-full bg-gradient-to-r from-violet-500 to-blue-500"
                    initial={{ width: 0 }}
                    animate={{ width: `${progress}%` }}
                    transition={{ duration: 0.8, ease: "easeOut" }}
                />
            </div>

            <AnimatePresence mode="wait">
                {state === "level3_ready" && blobUrl ? (
                    /* ── LEVEL 3: Play MP4 from Blob URL ─────────────────── */
                    <motion.div
                        key="blob-video"
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        className="aspect-video w-full bg-black"
                    >
                        <video
                            src={blobUrl}
                            controls
                            autoPlay
                            className="w-full h-full object-contain"
                            poster=""
                        />
                    </motion.div>
                ) : videoData ? (
                    /* ── LEVEL 1 & 2: Remotion Player (in-browser render) ── */
                    <motion.div
                        key="remotion-preview"
                        initial={{ opacity: 0, scale: 0.95 }}
                        animate={{ opacity: 1, scale: 1 }}
                        transition={{ type: "spring", stiffness: 200, damping: 20 }}
                        className="aspect-video w-full relative bg-black"
                    >
                        <Player
                            component={ConceptCardVideo}
                            durationInFrames={450}
                            compositionWidth={1280}
                            compositionHeight={720}
                            fps={24}
                            style={{ width: "100%", height: "100%" }}
                            controls
                            autoPlay
                            loop
                            inputProps={videoData}
                        />
                    </motion.div>
                ) : (
                    /* ── Loading state ──────────────────────────────────── */
                    <motion.div
                        key="loading"
                        className="aspect-video w-full flex flex-col items-center justify-center bg-gradient-to-br from-slate-900 to-black"
                    >
                        <Loader2 className="w-10 h-10 text-violet-400 animate-spin" />
                        <p className="text-slate-400 text-sm mt-4">Mempersiapkan video...</p>
                    </motion.div>
                )}
            </AnimatePresence>

            {/* Status overlay */}
            <div className="absolute top-4 left-4 bg-black/60 backdrop-blur-md px-3 py-1.5 rounded-full border border-white/10 flex items-center gap-2 pointer-events-none z-10">
                {state === "level2_enriching" || state === "level3_rendering" || state === "level3_queued" ? (
                    <Loader2 className="w-3 h-3 text-yellow-400 animate-spin" />
                ) : state === "level3_ready" ? (
                    <CheckCircle className="w-3 h-3 text-emerald-400" />
                ) : (
                    <Sparkles className="w-3 h-3 text-yellow-400" />
                )}
                <span className={`text-xs font-bold tracking-wide uppercase ${statusColor}`}>
                    {statusLabel}
                </span>
            </div>

            {/* MVP spec badge: 720p 24fps */}
            <div className="absolute bottom-4 right-4 bg-black/60 backdrop-blur-md px-2 py-1 rounded-md border border-white/10 pointer-events-none z-10">
                <span className="text-[10px] text-slate-500 font-mono">720p · 24fps</span>
            </div>
        </div>
    );
}
